[package]
name = "nitrate_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
anstyle = "1.0.11"
anstream = "0.6.20"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.2"
serde_json = "1.0.145"
lazy_static = "1.4.0"
json_comments = "0.2.2"
serde-xml-rs = "0.8.1"
serde = { version = "1.0.228", features = ["derive"] }
