[package]
name = "nitrate_diagnosis"
version = "0.1.0"
edition = "2024"

[dependencies]
slog = "2.7.0"
serde = { version = "1.0.219", features = ["derive"] }
bimap = "0.6.3"
once_cell = "1.21.3"
slog-async = "2.8.0"
slog-term = "2.9.2"
serde_json = "1.0.145"
